
#dbtype=oracle
#spring.datasource.url=jdbc:oracle:thin:@192.168.150.200:1521:ora11
#spring.datasource.username=wilson
#spring.datasource.password=wilson
#spring.driver-class-name=oracle.jdbc.driver.OracleDriver

#dbtype=sqlserver
#spring.datasource.url=jdbc:sqlserver://127.0.0.1:1433;DatabaseName=dbwzsoft;trustServerCertificate=true
#spring.datasource.username=sa
#spring.datasource.password=111111
#spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

#dbtype=mysql
#spring.datasource.url=jdbc:mysql://192.168.150.90:3306/dbwzsoft
#spring.datasource.username=admin
#spring.datasource.password=111111
#spring.datasource.driver-class-name=com.mysql.jdbc.Driver

dbtype=mysql
spring.datasource.url=jdbc:mysql://192.168.150.90:3306/dbwzsoft
spring.datasource.username=admin
spring.datasource.password=111111
spring.datasource.driver-class-name=com.mysql.jdbc.Driver


#dbtype=kingbase
#spring.datasource.driver-class-name=com.kingbase8.Driver
#spring.datasource.url=jdbc:kingbase8://192.168.150.201:54321/WZSOFT
#spring.datasource.username=admin
#spring.datasource.password=111111

#dbtype=dm
#spring.datasource.driver-class-name=dm.jdbc.driver.DmDriver
#spring.datasource.url=jdbc:dm://192.168.150.202:5236
#spring.datasource.username=DBADMIN
#spring.datasource.password=111111111

spring.redis.host=192.168.150.90
spring.redis.password=111111
spring.redis.port=6379

spring.mvc.pathmatch.matching-strategy=ant-path-matcher
filesvr=D:/Mywork/wsoftclaude/filesvr
webdir =/upload/**

# Enable multipart uploads
spring.servlet.multipart.enabled=true
# Threshold after which files are written to disk.
spring.servlet.multipart.file-size-threshold=2KB
# Max file size.
spring.servlet.multipart.max-file-size=200MB
# Max Request Size
spring.servlet.multipart.max-request-size=215MB
## File Storage Properties
# All files uploaded through the REST API will be stored in this directory
file.upload-dir=D:\\Mywork\\wsoftclaude\\filesvr\\uploadfiles\\datafiles
file.pdf-dir=D:\\Mywork\\wsoftclaude\\filesvr\\pdffiles


mailmode=ssl
mailpsndaynum=100
mailhost=smtp.163.com
mailusername=yourusername
mailpassword=yourpass

msgsign=235555
msgtmcode=SMS_464405318
msgkeyid=sags33323323
msgkeysecret=111111111111
msgpsndaynum=100

codefunc=function gcodejsfd(v,jpara){return gFloatEval(gFloatExps(v,jpara))};function repdbpara(para){var s=para+'';s = s.replace(/'/g, '');s = s.replace(/%/g, '');r='';var arr = s.split(',');for(var i=0;i<arr.length;i++){r = r + \"'\" + arr[i] + \"',\";}if(r.length>0){r=r.substring(0,r.length-1);}return r};function gaddlist(o,v){if(Object.prototype.toString.call(o) === '[object Array]'){o.push(v)}else{o.add(v)}};function setmsgpara(mp){for(var k in mp){if(k.indexOf('msg$')==0){mp[k]='';}}};function gcopyobj(obj){return JSON.parse(JSON.stringify(obj));};function gvalnum(v){if(v==null){return null};if(v==true&&(v+''=='true')){return true};if(v==false&&(v+''=='false')){return false};if(v=='undefined'){return undefined;};if(v=='[]'){return [];};if(v=='{}'){return {};};if(v==''){return v;};if(v=='null'){return null;};if(v=='true'){return true;};if(v=='false'){return false;};if(v&&v.toString().trim().length<80&&(v.toString().indexOf(':')>0||v.toString().indexOf('-')>0)){if(v instanceof Date){return v;};var vt=v;var regd = /^\\d{4}-\\d{1,2}-\\d{1,2}$/;var rd = regd.test(vt);var regt = /^\\d{4}-\\d{1,2}-\\d{1,2}(\\s|T)\\d{1,2}:\\d{1,2}:\\d{1,2}$/;var rt = regt.test(vt);if(rd||rt){if(vt.toString().indexOf(':')<0){vt=vt+ ' 00:00:00';};var dt = new Date(vt);if(dt!='Invalid Date'){return dt}}};if(isNaN(Number(v))){return v;}else{v=v+'';var s = v.trim();if(s==''){return v};if(s.indexOf('0')==0&&s.length>=2&&s.indexOf('.')!=1){return v};return Number(v);};};function gFloatIsOperator(value){var operatorString = "+-*/()";return operatorString.indexOf(value) > -1};function gFloatGetPrioraty(value){switch(value){case '+':case '-':return 1;case '*':case '/':return 2;default:return 0;}};function gFloatPrioraty(o1, o2){return gFloatGetPrioraty(o1) <= gFloatGetPrioraty(o2);};function gFloatExps(exp,jpara){var inputStack = [];var outputStack = [];var outputQueue = [];var st="";var bg=false;var tmpStack=[];for(var i = 0, len = exp.length; i < len; i++){var cur = exp[i];if(cur != ' ' ){st = st + cur + '';if(cur=='g'&&!bg){bg=true;}else if(bg){if(cur=='('){tmpStack.push('(');}else if(cur==')'){tmpStack.pop();if(tmpStack.length==0){bg=false;inputStack.push(jpara[st]);st ="";}}}else{inputStack.push(st);st ="";}}}while(inputStack.length > 0){var cur = inputStack.shift();if(gFloatIsOperator(cur)){if(cur == '('){outputStack.push(cur);}else if(cur == ')'){var po = outputStack.pop();while(po != '(' && outputStack.length > 0){outputQueue.push(po);po = outputStack.pop();}}else{while(gFloatPrioraty(cur, outputStack[outputStack.length - 1]) && outputStack.length > 0){outputQueue.push(outputStack.pop());}outputStack.push(cur);}}else{outputQueue.push(cur);}}if(outputStack.length > 0){while(outputStack.length > 0){outputQueue.push(outputStack.pop());}}return outputQueue;};function gFloatEval(rpnQueue){var outputStack = [];while(rpnQueue.length > 0){var cur = rpnQueue.shift();if(!gFloatIsOperator(cur)){outputStack.push(cur);}else{var sec = outputStack.pop();var fir = outputStack.pop();outputStack.push(gFloatResult(fir, sec, cur));}}return eval(outputStack[0]);};function gFloatResult(a, b, op){a=eval(a);b=eval(b);switch (op) {case '+':return gFloatAdd(a,b);case '-':return gFloatSub(a,b);case '*':return gFloatMul(a,b);case '/':return gFloatDiv(a,b);}};function gFloatAdd(arg1,arg2){var r1,r2,m;try{r1=arg1.toString().split(".")[1].length;}catch(e){r1=0;}try{r2=arg2.toString().split(".")[1].length;}catch(e){r2=0;}m=Math.pow(10,Math.max(r1,r2));return (arg1*m+arg2*m)/m;};function gFloatSub(arg1,arg2){var r1,r2,m,n;try{r1=arg1.toString().split(".")[1].length;}catch(e){r1=0;}try{r2=arg2.toString().split(".")[1].length;}catch(e){r2=0;}m=Math.pow(10,Math.max(r1,r2));n=(r1>=r2)?r1:r2;return ((arg1*m-arg2*m)/m).toFixed(n);};function gFloatMul(arg1,arg2){var m=0,s1=arg1.toString(),s2=arg2.toString();try{m+=s1.split(".")[1].length;}catch(e){}try{m+=s2.split(".")[1].length;}catch(e){}return Number(s1.replace(".",""))*Number(s2.replace(".",""))/Math.pow(10,m);};function gFloatDiv(arg1,arg2){var t1=0,t2=0,r1,r2;try{t1=arg1.toString().split(".")[1].length}catch(e){}try{t2=arg2.toString().split(".")[1].length}catch(e){}with(Math){r1=Number(arg1.toString().replace(".",""));r2=Number(arg2.toString().replace(".",""));return (r1/r2)*pow(10,t2-t1);}};
dataredistime=10000

gwebsite=http://localhost:8080/main-0.0.1-SNAPSHOT
loginpage=/manage/login.html

nacos.discovery.server-addr=127.0.0.1:8848
server.port=8080
spring.application.name=nacos-producer

taskrun=true